export const actionTypes = {
	LOADING_START: 'LOADING_START',
	FETCHING_DONE: 'FETCHING_DONE',
	SET_ERROR: 'SET_ERROR',
	LOADING_END: 'LOADING_END',
	CHANGE_QUERY: 'CHANGE_QUERY',
	CHANGE_SKIP: 'CHANGE_SKIP',
	TOGGLE_MODAL: 'TOGGLE_MODAL',
	OPEN_MODAL_CONTENT: 'OPEN_MODAL_CONTENT',
	NEXT_POST: 'NEXT_POST',
}
